---

# il n'est pas possible d'arrêter un service qui n'existe pas, il faut donc regarder s'il existe

- name: "postgres service est-il présent ?"
  become: true
  stat:
    path: "{{ postgres_service_path }}"
  register: postgres_service_exists

- name: "Arrêt du service"
  become: true
  service:
    name: postgres_service
    state: stopped
  when: postgres_service_exists.exists == false # les conditions évaluent les variables directement, sans '{{}}'. Pour des conditions plus complexes, voir le chapitre correspondant


- name: "Installation de postgres"
  become: true
  package:
    name: "postgres"
    state: present

- name: "Creation du user de postgres"
  become: true
  user:
    name: "{{ postgres_user }}"
    group: "{{ postgres_group }}"

- name: "lancement du service"
  become: true
  become_user: postgres
  service:
    name: postgres_service
    state: started